// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20241019135225_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            ProductName = "IPhone14",
                            price = 60000m
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            ProductName = "IPhone15",
                            price = 70000m
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = false,
                            ProductName = "IPhone16",
                            price = 80000m
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            ProductName = "IPhone17",
                            price = 90000m
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = true,
                            ProductName = "IPhone18",
                            price = 100000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
